name       : nitroshare-desktop
version    : 0.3.3
release    : 2
source     :
    - https://github.com/nitroshare/nitroshare-desktop/archive/0.3.3.tar.gz : 98a2a3faa53cad34e09777507ddf254f804f680a74d9aa4d33b445047796d02c
license    : MIT
component  : network.util
summary    : A cross-platform network file transfer application designed to make transferring any file to any device as painless as possible.
description: |
    A cross-platform network file transfer application designed to make transferring any file to any device as painless as possible.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    sed -i "s|Icon=nitroshare|Icon=/usr/share/icons/hicolor/scalable/apps/nitroshare.svg|" $installdir/usr/share/applications/nitroshare.desktop
