name       : nitroshare-desktop
version    : 0.3.4
release    : 4
source     :
    - https://github.com/nitroshare/nitroshare-desktop/archive/0.3.4.tar.gz : 29874e5909c29211a3c9e13f8c0f49b901ec2996e5d60d80af80d2fb80c3d7ec
license    : MIT
component  : network.util
summary    : A cross-platform network file transfer application designed to make transferring any file to any device as painless as possible.
description: |
    A cross-platform network file transfer application designed to make transferring any file to any device as painless as possible.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
setup      : |
    %patch -p1 < $pkgfiles/qt-5.11.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
    sed -i "s|Icon=nitroshare|Icon=/usr/share/icons/hicolor/scalable/apps/nitroshare.svg|" $installdir/usr/share/applications/nitroshare.desktop
